// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdgE8MaeGzhJLehS3NqWgB1qMMZ6V7-k',
    appId: '1:23608863291:android:032be7d39d808ebc3bca1e',
    messagingSenderId: '23608863291',
    projectId: 'flutter-learning-chat-ap-73507',
    storageBucket: 'flutter-learning-chat-ap-73507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwzkpvBxxgy1Rb03Qg7H-b7OGIKWZXAC0',
    appId: '1:23608863291:ios:4fafa506566bd90f3bca1e',
    messagingSenderId: '23608863291',
    projectId: 'flutter-learning-chat-ap-73507',
    storageBucket: 'flutter-learning-chat-ap-73507.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwzkpvBxxgy1Rb03Qg7H-b7OGIKWZXAC0',
    appId: '1:23608863291:ios:4fafa506566bd90f3bca1e',
    messagingSenderId: '23608863291',
    projectId: 'flutter-learning-chat-ap-73507',
    storageBucket: 'flutter-learning-chat-ap-73507.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}